graph TD;
    A[main()] --> B[Løsning av differensiallikninger med SymPy]
    B --> C[solve_first_order_ode_sympy()]
    B --> D[solve_nonlinear_ode_sympy()]
    B --> E[solve_second_order_ode_sympy()]
    B --> F[solve_third_order_ode_sympy()]
    A --> G[Løsning av differensiallikninger med PINNs (DeepXDE)]
    G --> H[solve_ode_pinn()]