classDiagram
class Main {
  +main()
}

class MathConcepts {
  +briggske_logaritmer()
  +kombinatorikk()
  +sannsynlighet_og_statistikk()
  +faser_og_faseoverganger()
  +varme_og_indre_energi()
  +termofysikkens_2_hovedsetning()
  +varmekapasitet_og_kalorimetri()
  +tallsystemer()
  +algoritmisk_tenking()
}

Main ..> MathConcepts : bruker