mindmap
  root((Algebra))
    Regneregler
    Brøk og prosentregning
    Potenser
    Tall på standardform
    Sammentrekning og faktorisering
    Likninger og formelregning
      Løse likninger av første og andre grad
      Løse likningssett med to ukjente
      Tilpasse og omforme formeluttrykk