graph TD
    A[Solve and Plot Linear] --> B[Løse Ligninger]
    B --> C[Konvertere Løsninger til Dikt]
    C --> D[Skriv Ut Løsninger]
    D --> E{To Variabler?}
    E -->|Ja| F[Plotting]
    E -->|Nei| End
    F --> G[Vis Plott]