mindmap
  root((Studieretningsspesifikke temaer))
    Briggske logaritmer
    Kombinatorikk
    Sannsynlighetsregning og statistikk
    Faser og faseoverganger
    Varme og indre energi
    Termofysikkens 2. hovedsetning
    Varmekapasitet og kalorimetri
    Tallsystemer
      Binære
      Desimale
      Heksadesimale
    Algoritmisk tenking
      Boolsk algebra
      Programmering av enkle algoritmer