name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Sjekk ut kode
      uses: actions/checkout@v2

    - name: Sett opp Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Init Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve