stages:
     - build
     - test
     - deploy

   build-job:
     stage: build
     script:
       - echo "Building the project..."
       - make build

   test-job:
     stage: test
     script:
       - echo "Running tests..."
       - make test

   deploy-job:
     stage: deploy
     script:
       - echo "Deploying the project..."
       - make deploy