apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-openshift-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/myorg/myrepo.git'
    path: 'openshift'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true