- name: Factoring
  hosts: localhost
  tasks:
    - name: Find common factors
      debug:
        msg: "Common factors: {{ num1 | factors | intersect(num2 | factors) }}"
      
    - name: Factor quadratic
      debug:
        msg: "Factors: {{ quadratic_expression | factor }}"
      
    - name: Factor difference of squares
      debug:
        msg: "Factors: {{ difference_of_squares | factor }}"