- name: SI Units and Decimal Prefixes
  hosts: localhost
  tasks:
    - name: Convert units
      debug:
        msg: "Converted units: {{ value | convert_units(to_unit) }}"
      
    - name: Use prefixes
      debug:
        msg: "With prefix: {{ value | use_prefix(prefix) }}"