- name: Vectors in the Plane
  hosts: localhost
  tasks:
    - name: Calculate magnitude
      debug:
        msg: "Magnitude: {{ (x**2 + y**2) | sqrt }}"
      
    - name: Calculate direction
      debug:
        msg: "Direction: {{ atan2(y, x) }}"
      
    - name: Add vectors
      debug:
        msg: "Sum of vectors: {{ vector1 + vector2 }}"
      
    - name: Subtract vectors
      debug:
        msg: "Difference of vectors: {{ vector1 - vector2 }}"