---
- name: Compliance Check Playbook
  hosts: all
  tasks:
    - name: Run compliance check script
      script: ../scripts/compliance_check.py
      register: compliance_result

    - name: Generate compliance report
      script: ../scripts/generate_report.py
      args:
        chdir: ../scripts/
        creates: compliance_report.txt
      when: compliance_result.changed

    - name: Propose corrective actions
      script: ../scripts/corrective_actions.py
      register: corrective_actions

    - name: Apply corrective actions
      script: ../scripts/apply_corrective_actions.py
      when: corrective_actions.changed

    - name: Verify corrective actions
      script: ../scripts/verify_actions.py
      register: verification_result

    - name: Final report
      script: ../scripts/generate_final_report.py
      args:
        chdir: ../scripts/
        creates: final_report.txt
      when: verification_result.changed