graph TD;
    A[Sikkerhetsledelse] --> B[Styring og risikohåndtering]
    A --> C[Ressurstildeling]
    A --> D[Hendelseshåndtering]
    A --> E[Kontinuerlig forbedring]
    F[Fysisk sikkerhet] --> G[Adgangskontroll]
    F --> H[Overvåkning]
    F --> I[Fysiske barrierer]
    F --> J[Sikkerhetspersonell]
    K[Personsikkerhet] --> L[Bakgrunnssjekk]
    K --> M[Sikkerhetsopplæring]
    K --> N[Klare roller og ansvar]
    K --> O[Overvåkning og etterlevelse]
    P[IKT-sikkerhet] --> Q[Nettverkssikkerhet]
    P --> R[Systemintegritet]
    P --> S[Databeskyttelse]
    P --> T[Bevissthet om cybersikkerhet]