# Logstash konfigurasjonsfil
input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "iot-logs-%{+YYYY.MM.dd}"
  }
}

# Filebeat konfigurasjonsfil på IoT-enheten
filebeat.inputs:
- type: log
  paths:
    - /var/log/iot/*.log

output.logstash:
  hosts: ["localhost:5044"]