- name: Automatiser sikkerhetsoppdateringer
  hosts: all
  become: yes
  tasks:
    - name: Installer unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present

    - name: Konfigurer automatiske oppdateringer
      lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        line: '{{ item }}'
      with_items:
        - 'APT::Periodic::Update-Package-Lists "1";'
        - 'APT::Periodic::Unattended-Upgrade "1";'