- name: Work, Power, and Efficiency
  hosts: localhost
  tasks:
    - name: Calculate work
      debug:
        msg: "Work: {{ force * distance }}"
      
    - name: Calculate power
      debug:
        msg: "Power: {{ work / time }}"
      
    - name: Calculate efficiency
      debug:
        msg: "Efficiency: {{ (useful_energy_output / total_energy_input) * 100 }}%"