- name: Algebra Rules
  hosts: localhost
  tasks:
    - name: Perform addition
      debug:
        msg: "Addition: {{ a + b }}"
    - name: Perform subtraction
      debug:
        msg: "Subtraction: {{ a - b }}"
    - name: Perform multiplication
      debug:
        msg: "Multiplication: {{ a * b }}"
    - name: Perform division
      debug:
        msg: "Division: {{ a / b }}"