apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  tasks:
    - name: build
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: quay.io/myrepo/myapp:latest
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: deploy-kubernetes-manifests
      params:
        - name: manifests
          value: "k8s/deployment.yaml"