mindmap
root((Data Security Risks))
  Data Breaches
  Misconfiguration and Inadequate Change Control
  Lack of Cloud Security Architecture and Strategy
  Insufficient Identity, Credential, Access and Key Management
  Account Hijacking
  Insider Threats
  Insecure Interfaces and APIs
  Weak Control Plane
  Limited Cloud Usage Visibility
  Abuse and Nefarious Use of Cloud Services