mindmap
  root((Verktøy og ressurser for feilsøking))
    Logger
      Systemlogger
      Applikasjonslogger
      Sikkerhetslogger
      Nettverkslogger
    Debuggere
      Verktøy for å kjøre programmer trinnvis
      Undersøke hva som skjer i minnet og registrene
    Nettverksanalyse-verktøy
      Wireshark
      tcpdump
    Online fora og communities
      Stack Exchange
      Reddit