mindmap
  root((Sentrale begreper og konsepter))
    Uke 1
      Sikkerhetstriaden CIA
        Konfidensialitet
        Integritet
        Tilgjengelighet
      Trusler
        Malware
        Phishing
        Sosial manipulasjon
        Zero-day sårbarheter
      Nettverk
        TCP/IP
        OSI-modellen
        Brannmurer
        VPN
        IDS IPS
      Sikkerhetspolicyer
        Akseptabel bruk
        Passordpolitikk
        Hendelseshåndtering
      Kryptografi
        Symmetrisk kryptering
        Asymmetrisk kryptering
        Hashing
        Digitale signaturer
      Endepunktsikkerhet
        Antivirus
        EDR
        DLP
        Mobil sikkerhet
    Uke 2
      Brannmurer
        Stateful inspection
        Deep packet inspection
        Application-layer gateways
      IDS IPS
        Signaturbasert deteksjon
        Anomalibasert deteksjon
      DDoS
        Typer angrep
        Mitigering
      Nettverksovervåking
        Wireshark
        NetFlow IPFIX
        Trusselintelligens
      Sikker nettverksarkitektur
        Defense in depth
        Segmentering
        DMZ
        NAT
        Port forwarding
      VPN
        IPsec
        SSL TLS
        OpenVPN
      SIEM
        Logginnsamling
        Normalisering
        Korrelasjon
        Varsling
        Rapportering
    Uke 3
      IAM
        Identitetsadministrasjon
        Autentisering
        Autorisasjon
        Tilgangsrevisjon
      MFA
        Faktorer noe du vet, har, er
        Implementeringer OTP, push, biometri
      Tilgangskontroll
        DAC
        MAC
        RBAC
        ABAC
        Minste privilegium
      IGA
        Brukerlivssyklus
        Tilgangsforespørsler
        Revisjoner
        PAM
      Identitetsbeskyttelse
        Trusler
        Beste praksis
        Verktøy
    Uke 4
      Hendelsesrespons
        Livssyklus
        Forberedelse
        Identifisering
        Inneslutning
        Utryddelse
        Gjenoppretting
        Lærdom
      Deteksjon og analyse
        Signaturbasert deteksjon
        Anomalibasert deteksjon
        Heuristisk deteksjon
        Behavior-basert deteksjon
        SIEM
        IDS IPS
        EDR
        Trusselintelligens
      Inneslutning, utryddelse og gjenoppretting
        Isolering
        Blokkering
        Deaktivering
        Fjerning av malware
        Patching
        Datagjenoppretting
      Trusseljakt
        Proaktiv tilnærming
        Hypotesetesting
        Datainnsamling
        Analyse
      Digital etterforskning
        Prinsipper
        Prosess
        Verktøy
      Malware-analyse
        Statisk analyse
        Dynamisk analyse
        Sandboxing
      Hendelseshåndteringssystemer
        Ticketing
        Workflow
        SOAR