mindmap
  root((Mål for Dagen))
    Forstå betydningen av cybersikkerhet
      Hvorfor cybersikkerhet er avgjørende i dagens digitale verden
      Konsekvensene av manglende sikkerhet for både enkeltpersoner og organisasjoner
    Bli kjent med grunnleggende begreper
      Introduksjon til viktige cybersikkerhetsbegreper og terminologi
      Forståelse av begreper som malware, phishing, firewall, encryption, etc.
    Identifisere vanlige trusler
      Lære om de mest vanlige cybertruslene
        phishing
        malware
        ransomware
        DDoS-angrep
        social engineering
      Hvordan disse truslene fungerer og hvordan de kan påvirke systemer og data
    Forstå CIA-triaden
      Konfidensialitet
        Beskyttelse av informasjon fra uautorisert tilgang
      Integritet
        Sikre at informasjon er korrekt og uendret
      Tilgjengelighet
        Sikre at informasjon og systemer er tilgjengelige når de trengs