mindmap
  root((Skysikkerhet))
    Skyplattformer
      AWS (Amazon Web Services)
        Sikkerhetsgrupper
        IAM-roller
        S3-bucket-policyer
        Andre sikkerhetsmekanismer
      Azure
        Sikkerhetsgrupper
        Nettverkssikkerhetsgrupper
        Azure Active Directory
        Andre sikkerhetsfunksjoner
      GCP (Google Cloud Platform)
        Identity and Access Management (IAM)
        Brannmurregler
        Cloud Armor
        Andre sikkerhetstiltak
    Sikkerhetsovervåking og logging
      CloudTrail (AWS)
        Logge API-kall
        Andre hendelser i AWS
      Azure Monitor
        Samle inn og analysere logger fra Azure-ressurser
      Stackdriver (GCP)
        Overvåke og logge hendelser i GCP