graph TD
    A[studieretning_modul.js] --> B[studieretning_meny]
    B --> C[briggskeLogaritmer]
    B --> D[kombinatorikk]
    B --> E[sannsynlighetOgStatistikk]
    B --> F[faserOgFaseoverganger]
    B --> G[varmeOgIndreEnergi]
    B --> H[termofysikkensAndreLov]
    B --> I[varmekapasitetOgKalorimetri]
    B --> J[tallsystemer]
    B --> K[algoritmiskTenking]
    C --> L[Visning]
    D --> M[Visning]
    E --> N[Visning]
    F --> O[Visning]
    G --> P[Visning]
    H --> Q[Visning]
    I --> R[Visning]
    J --> S[Visning]
    K --> T[Visning]