graph TD
    A[funksjoner_modul.js] --> B[funksjoner]
    B --> C[retteLinjer]
    B --> D[polynomfunksjoner]
    B --> E[eksponentialfunksjoner]
    B --> F[derivasjonAvPolynomfunksjoner]
    B --> G[regresjon]
    C --> H[Visning]
    D --> I[Visning]
    E --> J[Visning]
    F --> K[Visning]
    G --> L[Visning]