graph TD
    subgraph algebra_modul.js
        A[regneregler] --> B[Vis inputfelter]
        A --> C[Utfør beregninger]
        A --> D[Vis resultater]
        B --> E[DOM Manipulasjon]
        C --> F[Beregninger]
        D --> G[DOM Manipulasjon]
    end