flowchart TD
    A[Hovedmeny] -->|Klikk| B(Mathematikk)
    A -->|Klikk| C(Fysikk)
    A -->|Klikk| D(Studieretningsspesifikke Temaer)
    B -->|Klikk| B1[Algebra]
    B -->|Klikk| B2[Trigonometri og Geometri]
    B -->|Klikk| B3[Funksjoner]
    C -->|Klikk| C1[Innledende Fysikk]
    C -->|Klikk| C2[Kraft og Rettlinjet Bevegelse]
    C -->|Klikk| C3[Energi og Arbeid]
    C -->|Klikk| C4[Termodynamikk]
    D -->|Klikk| D1[Briggske Logaritmer]
    D -->|Klikk| D2[Kombinatorikk]
    D -->|Klikk| D3[Sannsynlighetsregning og Statistikk]
    D -->|Klikk| D4[Faser og Faseoverganger]
    D -->|Klikk| D5[Varme og Indre Energi]
    D -->|Klikk| D6[Termofysikkens 2. Hovedsetning]
    D -->|Klikk| D7[Varmekapasitet og Kalorimetri]
    D -->|Klikk| D8[Tallsystemer]
    D -->|Klikk| D9[Algoritmisk Tenking]