graph LR
    subgraph Main Menu
        A[Main Menu] --> B(Mathematics)
        A[Main Menu] --> C(Physics)
        A[Main Menu] --> D(Specialized Topics)
    end
    
    subgraph Mathematics
        B(Mathematics) --> B1(Algebra)
        B(Mathematics) --> B2(Trigonometry & Geometry)
        B(Mathematics) --> B3(Functions & Graphs)
    end
    
    subgraph Physics
        C(Physics) --> C1(Introductory Physics)
        C(Physics) --> C2(Force & Motion)
        C(Physics) --> C3(Energy)
        C(Physics) --> C4(Thermodynamics)
    end
    
    subgraph Specialized Topics
        D(Specialized Topics) --> D1(Logarithms)
        D(Specialized Topics) --> D2(Combinatorics)
        D(Specialized Topics) --> D3(Probability & Statistics)
        D(Specialized Topics) --> D4(Phases & Transitions)
        D(Specialized Topics) --> D5(Heat & Energy)
        D(Specialized Topics) --> D6(Thermodynamics 2nd Law)
        D(Specialized Topics) --> D7(Heat Capacity)
        D(Specialized Topics) --> D8(Number Systems)
        D(Specialized Topics) --> D9(Algorithmic Thinking)
    end