sequenceDiagram
    autonumber
    participant Bruker
    participant LærerApp
    participant AlgebraModul
    participant TrigonometriGeometriModul
    participant FunksjonerModul
    participant FysikkModul
    participant StudieretningModul

    Bruker->>LærerApp: Klikk på "Matematikk"
    LærerApp->>AlgebraModul: byggMatematikkMeny()
    AlgebraModul-->>LærerApp: Vis meny
    Bruker->>LærerApp: Klikk på "Algebra"
    LærerApp->>AlgebraModul: algebra_meny()
    AlgebraModul-->>LærerApp: Vis Algebra meny
    Bruker->>LærerApp: Klikk på "Regneregler"
    LærerApp->>AlgebraModul: regneregler()
    AlgebraModul-->>LærerApp: Vis inputfelter og forklaring
    Bruker->>LærerApp: Skriv inn verdier og klikk "Beregn"
    LærerApp->>AlgebraModul: Utfør beregninger
    AlgebraModul-->>LærerApp: Vis resultater