graph TD
    A[fysikk_modul.js] --> B[fysikk_meny]
    B --> C[innledendeFysikk]
    B --> D[kraftOgRettlinjetBevegelse]
    B --> E[energiOgArbeid]
    B --> F[termodynamikk]
    C --> G[Visning]
    D --> H[Visning]
    E --> I[Visning]
    F --> J[Visning]