journey
    title Brukerens Reise på Læringsplattformen
    section Start
      Klikk på hovedmeny: 5: Bruker
    section Velg Emne
      Velg matematikk: 4: Bruker
      Velg fysikk: 4: Bruker
      Velg studieretning: 4: Bruker
    section Utforsk Undermeny
      Velg algebra: 3: Bruker
      Velg trigonometri: 3: Bruker
      Velg funksjoner: 3: Bruker
      Velg fysikk: 3: Bruker
      Velg studieretningsspesifikke emner: 3: Bruker
    section Løs Oppgaver
      Løs algebraoppgave: 2: Bruker
      Løs geometrioppgave: 2: Bruker
      Løs fysikkoppgave: 2: Bruker
      Løs studieretningsspes

ifikk oppgave: 2: Bruker