graph TD
    A[Hovedmeny] --> B(Mathematikk)
    A --> C(Fysikk)
    A --> D(Studieretningsspesifikke Temaer)
    B --> B1[Algebra]
    B --> B2[Trigonometri og Geometri]
    B --> B3[Funksjoner]
    C --> C1[Innledende Fysikk]
    C --> C2[Kraft og Rettlinjet Bevegelse]
    C --> C3[Energi og Arbeid]
    C --> C4[Termodynamikk]
    D --> D1[Briggske Logaritmer]
    D --> D2[Kombinatorikk]
    D --> D3[Sannsynlighetsregning og Statistikk]
    D --> D4[Faser og Faseoverganger]
    D --> D5[Varme og Indre Energi]
    D --> D6[Termofysikkens 2. Hovedsetning]
    D --> D7[Varmekapasitet og Kalorimetri]
    D --> D8[Tallsystemer]
    D --> D9[Algoritmisk Tenking]