mindmap
  root((Økonomistyring, Organisasjon og Ledelse, Markedsføringsledelse))
    Økonomistyring
      Etablering av Bedrift
        Selskapsform
        Argumenter
      Budsjettering og Budsjettkontroll
        Tiltak ved lavere omsetning
      Nøkkeltallsanalyse
        Likviditetsgrad
      Investeringsanalyse
        Initiale kostnader
        Levetid
        Vedlikeholdskostnader
        Inntekter
      Kostnadsstyring
        Kostnadsreduksjon uten å påvirke produktkvalitet
    Organisasjon og Ledelse
      Teamledelse og Motivasjon
        Tilbakemeldinger
        Karriereplaner
        Lønn og bonuser
      Lederstil
        Autoritær
        Transformasjonsledelse
        Laissez-faire
      Endringsledelse
        Omstrukturering
      Konflikthåndtering
        Åpen diskusjon
      Kompetanseutvikling
        Kompetansekartlegging
        Skreddersydd opplæring
    Markedsføringsledelse
      Digital Markedsføringskampanje
        Sosiale medier
        SEO-optimalisering
        PPC-annonsering
      Markedsanalyse
        Markedsundersøkelse
        Kundebehov
        Konkurranse
      Produktlansering
        Markedsføringsplan
      Kunderelasjoner
        Kundelojalitetsprogram