gitGraph
   commit id: "Initielt kampanjeoppsett"
   branch oppdatering1
   commit id: "Justering 1"
   checkout main
   merge oppdatering1 id: "Slå sammen justering 1"
   branch oppdatering2
   commit id: "Justering 2"
   checkout main
   merge oppdatering2 id: "Slå sammen justering 2"