C4Context
title System Context diagram for Oracle LiveSQL

Enterprise_Boundary(e0, "Oracle LiveSQL") {
    Person(user, "User", "A person looking to learn various database skills")

    System(oracleLabs, "Oracle Database Hands-On Labs", "Experiment with Oracle Database directly in the browser without installing anything locally")
}

Rel(user, oracleLabs, "Learns Oracle Database with")