classDiagram
    class Organisasjon {
        +String navn
        +String orgNr
        +leggTilAvdeling(avdeling)
        +fjernAvdeling(avdeling)
    }

    class Avdeling {
        +String navn
        +String leder
        +leggTilAnsatt(ansatt)
        +fjernAnsatt(ansatt)
    }

    class Ansatt {
        +String navn
        +String stilling
        +ansett()
        +siOpp()
    }