mindmap
  root((Tema: Økonomistyring, Organisasjon og Ledelse, Markedsføringsledelse))
    Læringsutbytte
      Kunnskap
        Sentrale begreper
        Lønnskostnader
        Mål, tiltak og handlingsplaner
        Lover og avtaler
      Ferdigheter
        Kartlegge arbeidsbetingelser
        Økonomisk status og analyser
        Vurdere betalingsevne og kapitalbehov
        Planlegge økonomiske milepæler og budsjetter
        Investeringer og lønnsomhetsanalyse
        Bruk av regneark
        Helhetlig prisvurdering
        Organisasjonsstruktur og arbeidsmiljø
        Kommunisere, lede og motivere ansatte
        Identifisere og utvikle kompetanse
        Rekrutteringsprosesser
        Kjøpsprosess og kundens kjøpsatferd
        Markedskommunikasjon og tilpasning
        Produktsatsing og markedsvalg
        Virksomhets- og markedsstrategier
      Generell kompetanse
        Planlegge og gjennomføre arbeidsoppgaver
        Lede organisasjon med fokus på effektivitet og samfunnsansvar
        Digital kompetanse og bruk av informasjon
        Kommunikasjon og digitale verktøy
        Utarbeide faglige dokumenter
        Refleksjon over samfunnsutvikling
    Arbeidskrav
      Aktiv deltakelse i opplæringen
      Deltagelse i gruppearbeid og prosjekter
      Forberede seg til undervisning
      Minst 80% oppmøte
      Bidra til læring i gruppen
      Deltakelse på veilednings- og evalueringsmøter
      Gjennomføre og få godkjent spesifikke arbeidskrav
      Vurderingskriterier fastsatt av lærer
    Pensumlitteratur
      Økonomistyring: LØM, Holan, Høiseth
      Markedsføringsledelse: LØM, Holan
      Organisasjon og ledelse, Holan, Høiseth
      Økonomi for ikke-økonomer, Learning by doing AS