mindmap
  root((Learning Path for FTD02H-N))
    Intro((Introduction))
      Overview((Course Overview))
      Objectives((Learning Objectives))
    Basics((Basic Concepts))
      NetworkFund((Networking Fundamentals))
      Protocols((Common Protocols))
    Intermediate((Intermediate Topics))
      Firewalls((Firewalls and Security))
      VPNs((VPN Configuration))
    Advanced((Advanced Topics))
      Intrusion((Intrusion Detection Systems))
      Policies((Security Policies))
    HandsOn((Hands-on Labs))
      Lab1((Lab 1: Basic Configuration))
      Lab2((Lab 2: Advanced Security Settings))
      Lab3((Lab 3: VPN Setup))
    Resources((Additional Resources))
      Docs((Documentation))
      Forums((Community Forums))
      Videos((Video Tutorials))