C4Context
title System Context diagram for Microsoft Learn

Enterprise_Boundary(e0, "Microsoft Learn") {
    Person(user, "User", "A person looking to learn various database skills")

    System(azureSQL, "Azure SQL Database", "Learn to create, manage, and scale relational databases in the cloud with Microsoft Azure SQL Database")
    System(sqlServerVM, "SQL Server on Virtual Machines", "Explore how to run SQL Server on virtual machines in Azure for increased flexibility and control")
}

Rel(user, azureSQL, "Learns Azure SQL with")
Rel(user, sqlServerVM, "Learns SQL Server on VMs with")