mindmap
  root((Organisasjonskultur))
    Steg for Kulturendring
      Definere ønsket kultur
        Verdier
        Normer
        Atferd
      Kommunisere visjonen
        Møter
        Intranett
        Sosiale medier
      Endre atferd
        Lederatferd
        Belønningssystemer
      Involvere ansatte
        Utvikling
        Implementering
      Symbolsk handling
        Symboler
        Ritualer
    Utfordringer
      Motstand mot endring
      Tidkrevende prosess
      Inkonsistens