mindmap
  root((Økonomistyring, Organisasjon og Ledelse, Markedsføringsledelse))
    Økonomistyring
      Etablering av Bedrift
        Selskapsform
        Argumenter
      Budsjettering og Budsjettkontroll
        Tiltak ved lavere omsetning
      Nøkkeltallsanalyse
        Likviditetsgrad
    Organisasjon og Ledelse
      Teamledelse og Motivasjon
        Tiltak
      Lederstil
        Løsninger
      Endringsledelse
        Omstrukturering
    Markedsføringsledelse
      Digital Markedsføringskampanje
        Strategier