mindmap
  root((Læringsutbytte i Økonomistyring))
    Kunnskap
      Sentrale begreper
      Lønnskostnader
      Mål, tiltak og handlingsplaner
      Lover og avtaler
    Ferdigheter
      Kartlegge arbeidsbetingelser
      Økonomisk status og analyser
      Vurdere betalingsevne og kapitalbehov
      Planlegge økonomiske milepæler og budsjetter
      Investeringer og lønnsomhetsanalyse
      Bruk av regneark
    Generell kompetanse
      Planlegge og gjennomføre arbeidsoppgaver
      Lede organisasjon med fokus på effektivitet og samfunnsansvar
      Digital kompetanse og bruk av informasjon
      Kommunikasjon og digitale verktøy