mindmap
  root((Kompetanseutvikling og Motivasjon))
    Kartlegging av kompetansebehov
      Medarbeidersamtaler
      Spørreundersøkelser
      Kompetansekartlegging
      Observasjon
    Tiltak for å dekke behov og øke motivasjon
      Kurs og opplæring
      Mentoring og coaching
      Jobbrotasjon
      E-læring
      Anerkjennelse og belønning
    Måling av effekt
      Evalueringsskjemaer
      Prestasjonsmålinger
      Medarbeiderundersøkelser