C4Context
title System Context diagram for SQLZoo

Enterprise_Boundary(e0, "SQLZoo") {
    Person(user, "User", "A person looking to test their SQL knowledge")

    System(sqlZoo, "SQL Practice", "Test your SQL skills with a variety of challenges and exercises")
}

Rel(user, sqlZoo, "Practices SQL with")