flowchart TD
    Start --> A[Generell Kompetanse]
    
    A --> B{Har du en helhetlig forståelse av trusselbildet?}
    B -->|Ja| B1[Flott!]
    B -->|Nei| B2[Les mer om trusselbildet]
    
    A --> C{Kan du kommunisere effektivt om sikkerhetsrisikoer og tiltak?}
    C -->|Ja| C1[Flott!]
    C -->|Nei| C2[Øv mer på kommunikasjon om sikkerhetsrisikoer]
    
    A --> D{Kan du bidra til å skape en sikkerhetsbevisst kultur i organisasjonen?}
    D -->|Ja| D1[Flott!]
    D -->|Nei| D2[Les mer om å skape en sikkerhetsbevisst kultur]