flowchart TD
    Start --> A[Energibevaring]
    
    A --> B{Hva er loven om energibevaring?}
    B -->|Energi kan verken skapes eller ødelegges| B1[Flott! Du kjenner loven om energibevaring.]
    B -->|Feil| B2[Du må øve mer. Gå til Conservation of Energy Labs]