flowchart TD
    Start --> A[Kunnskap]
    
    A --> B{Kan du identifisere ulike typer trusler?}
    B -->|Ja| B1[Flott!]
    B -->|Nei| B2[Les mer om vanlige trusler]
    
    A --> C{Kan du identifisere ulike trusselaktører?}
    C -->|Ja| C1[Flott!]
    C -->|Nei| C2[Les mer om trusselaktører]
    
    A --> D{Forstår du deres motiver og taktikker?}
    D -->|Ja| D1[Flott!]
    D -->|Nei| D2[Les mer om motiver og taktikker]
    
    A --> E{Kjenner du til vanlige angrepsvektorer og sårbarheter?}
    E -->|Ja| E1[Flott!]
    E -->|Nei| E2[Les mer om angrepsvektorer og sårbarheter]