flowchart TD
    Start --> A[Termodynamikkens Første Lov

]
    
    A --> B{Hva sier termodynamikkens første lov?}
    B -->|Energi kan verken skapes eller ødelegges, bare omformes| B1[Flott! Du kjenner termodynamikkens første lov.]
    B -->|Feil| B2[Du må øve mer. Gå til Thermodynamics Labs]