flowchart TD
    Start --> A[Internasjonale og Regionale Lover]
    
    A --> B{Hva er GDPR?}
    B -->|Beskytter personopplysninger til individer i EU og EØS| B1[Flott!]
    B -->|Feil| B2[Les mer om GDPR]
    
    B2 --> C{Hva er kravene til GDPR?}
    C -->|Samtykke, rett til tilgang, rett til å bli glemt, dataportabilitet, meldingsplikt ved databrudd| C1[Flott!]
    C -->|Feil| C2[Les mer om GDPR Krav]
    
    B2 --> D{Hva er sanksjonene for brudd på GDPR?}
    D -->|Bøter på opptil 4% av global omsetning eller 20 millioner euro| D1[Flott!]
    D -->|Feil| D2[Les mer om GDPR Sanksjoner]
    
    A --> E{Hva er HIPAA?}
    E -->|Beskytter pasientdata i USA| E1[Flott!]
    E -->|Feil| E2[Les mer om HIPAA]
    
    E2 --> F{Hva er kravene til HIPAA?}
    F -->|Personvernregel, sikkerhetsregel, bruddvarslingsregel| F1[Flott!]
    F -->|Feil| F2[Les mer om HIPAA Krav]
    
    E2 --> G{Hva er sanksjonene for brudd på HIPAA?}
    G -->|Bøter og straffeforfølgelse| G1[Flott!]
    G -->|Feil| G2[Les mer om HIPAA Sanksjoner]