flowchart TD
    Start --> A[Nasjonale Lover]
    
    A --> B{Hva er Personopplysningsloven?}
    B -->|Implementerer GDPR i norsk lov| B1[Flott!]
    B -->|Feil| B2[Les mer om Personopplysningsloven]
    
    B2 --> C{Hva er kravene til Personopplysningsloven?}
    C -->|Samme som GDPR| C1[Flott!]
    C -->|Feil| C2[Les mer om Personopplysningsloven Krav]
    
    B2 --> D{Hva er sanksjonene for brudd på Personopplysningsloven?}
    D -->|Bøter og straffeforfølgelse| D1[Flott!]
    D -->|Feil| D2[Les mer om Personopplysningsloven Sanksjoner]
    
    A --> E{Hva er Sikkerhetsloven?}
    E -->|Beskytter nasjonal sikkerhet, herunder IKT-systemer| E1[Flott!]
    E -->|Feil| E2[Les mer om Sikkerhetsloven]
    
    E2 --> F{Hva er kravene til Sikkerhetsloven?}
    F -->|Sikkerhetstiltak, risikostyring, hendelseshåndtering| F1[Flott!]
    F -->|Feil| F2[Les mer om Sikkerhetsloven Krav]
    
    E2 --> G{Hva er sanksjonene for brudd på Sikkerhetsloven?}
    G -->|Bøter og straffeforfølgelse| G1[Flott!]
    G -->|Feil| G2[Les mer om Sikkerhetsloven Sanksjoner]