flowchart TD
    Start --> A[Muntlig kommunikasjon]
    
    A --> B[italki]
    B -->|Finn en språktandem partner for å øve på å snakke engelsk| B1[🔗 [Link](https://www.italki.com/)]
    
    A --> C[Cambly]
    C -->|Få tilgang til engelsklærere online for samtaler og tilbakemeldinger| C1[🔗 [Link](https://www.cambly.com/)]