flowchart TD
    Start --> A[Ferdigheter]
    
    A --> B{Kan du implementere nødvendige tiltak for å sikre samsvar med lover og regler?}
    B -->|Ja| B1[Flott!]
    B -->|Nei| B2[Øv mer på implementering]
    
    A --> C{Kan du utvikle og vedlikeholde dokumentasjon og prosedyrer?}
    C -->|Ja| C1[Flott!]
    C -->|Nei| C2[Øv mer på dokumentasjon og prosedyrer]
    
    A --> D{Kan du gjennomføre risikovurderinger og implementere sikkerhetskontroller?}
    D -->|Ja| D1[Flott!]
    D -->|Nei| D2[Øv mer på risikovurdering og sikkerhetskontroller]