flowchart TD
    Start --> A[Kritisk tenkning og kildebruk]
    
    A --> B[Faktisk.no]
    B -->|Lær å faktasjekke informasjon og avsløre falske nyheter| B1[🔗 [Link](https://faktisk.no/)]
    
    A --> C[Kritisk Mediekompetanse]
    C -->|Utforsk ressurser og øvelser for å utvikle kritisk medieforståelse| C1[🔗 [Link](https://www.medietilsynet.no/)]