flowchart TD
    Start --> A[Grammatikk og Vokabular]
    
    A --> B[Duolingo]
    B -->|Lær engelsk på en morsom og interaktiv måte med spill og øvelser| B1[🔗 [Link](https://www.duolingo.com/)]
    
    A --> C[Grammarly]
    C -->|Få tilbakemelding på grammatikk og skrivestil i sanntid| C1[🔗 [Link](https://www.grammarly.com/)]
    
    A --> D[EnglishClub]
    D -->|Finn grammatikkforklaringer, øvelser og ressurser for å forbedre engelskkunnskapene dine| D1[🔗 [Link](https://www.englishclub.com/)]