flowchart TD
    Start --> A[Generell Kompetanse]
    
    A --> B{Kan du integrere compliance i organisasjonens sikkerhetskultur?}
    B -->|Ja| B1[Flott!]
    B -->|Nei| B2[Les mer om compliance og sikkerhetskultur]
    
    A --> C{Kan du kommunisere effektivt om juridiske krav og sikkerhetstiltak?}
    C -->|Ja| C1[Flott!]


    C -->|Nei| C2[Øv mer på kommunikasjon]
    
    A --> D{Kan du holde deg oppdatert på endringer i lover og regler?}
    D -->|Ja| D1[Flott!]
    D -->|Nei| D2[Les mer om å holde seg oppdatert]