flowchart TD
    Start --> A[Bransjespesifikke Standarder]
    
    A --> B{Hva er PCI DSS?}
    B -->|Standard for å beskytte kortdata ved transaksjoner| B1[Flott!]
    B -->|Feil| B2[Les mer om PCI DSS]
    
    B2 --> C{Hva er kravene til PCI DSS?}
    C -->|Sikkerhetsnettverk, kryptering, sårbarhetsstyring, tilgangskontroll, overvåking, informasjonssikkerhetspolicy| C1[Flott!]
    C -->|Feil| C2[Les mer om PCI DSS Krav]
    
    B2 --> D{Hva er sanksjonene for brudd på PCI DSS?}
    D -->|Bøter og tap av muligheten til å behandle korttransaksjoner| D1[Flott!]
    D -->|Feil| D2[Les mer om PCI DSS Sanksjoner]