flowchart TD
    Start --> A[Vanlige Trusler]
    
    A --> B{Hva er Malware?}
    B -->|Ondsinnet Programvare| B1[Flott!]
    B -->|Feil| B2[Les mer om Malware]
    
    B2 --> Virus[Les mer om Virus]
    B2 --> Trojanere[Les mer om Trojanere]
    B2 --> Ormer[Les mer om Ormer]
    B2 --> Spyware[Les mer om Spyware]
    B2 --> Ransomware[Les mer om Ransomware]
    
    A --> C{Hva er Phishing?}
    C -->|Falske e-poster, meldinger eller nettsider| C1[Flott!]
    C -->|Feil| C2[Les mer om Phishing]
    
    A --> D{Hva er Social Engineering?}
    D -->|Manipulering av mennesker| D1[Flott!]
    D -->|Feil| D2[Les mer om Social Engineering]
    
    A --> E{Hva er Man-in-the-Middle (MitM) Angrep?}
    E -->|Avlytting og endring av kommunikasjon| E1[Flott!]
    E -->|Feil| E2[Les mer om MitM Angrep]
    
    A --> F{Hva er Zero-Day Exploits?}
    F -->|Utnyttelse av ukjente sårbarheter| F1[Flott!]
    F -->|Feil| F2[Les mer om Zero-Day Exploits]
    
    A --> G{Hva er DDoS-angrep?}
    G -->|Overbelastning av systemer| G1[Flott!]
    G -->|Feil| G2[Les mer om DDoS-angrep]
    
    A --> H{Hva er SQL-injeksjon?}
    H -->|Injisering av ondsinnet kode i SQL-spørringer| H1[Flott!]
    H -->|Feil| H2[Les mer om SQL-injeksjon]