flowchart TD
    Start --> A[Skriveferdigheter]
    
    A --> B[Norsksidene]
    B -->|Lær norsk grammatikk, rettskriving og tegnsetting gjennom interaktive øvelser og tester| B1[🔗 [Link](https://www.norsksidene.no/)]
    
    A --> C[Skrivesenteret]
    C -->|Få hjelp med å forbedre skrivingen din gjennom veiledninger, eksempler og skriveøvelser| C1[🔗 [Link](https://www.skrivesenteret.no/)]
    
    A --> D[Norsk Språkråd]
    D -->|Få tilgang til offisielle regler og veiledninger for norsk språkbruk| D1[🔗 [Link](https://www.sprakradet.no/)]