usecaseDiagram
    actor Bruker
    Bruker --> (Logge inn)
    Bruker --> (Søke)
    Bruker --> (Bestille)
    Bruker --> (Betale)
    
    (Logge inn) .> (Søke) : <<inkluderer>>
    (Bestille) .> (Betale) : <<inkluderer>>